[package]
name = "dash_wasm_engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
leb128 = "0.2.5"
thiserror = "1.0.37"
byteorder = "1.4.3"
strum_macros = "0.24.3"
